
'use client';

import dynamic from 'next/dynamic';
const ROASCalculator = dynamic(() => import('../../../components/ROASCalculator'), { ssr: false });
import Navbar from '@/components/NavBar';
import Footer from '@/components/Footer';
import Head from 'next/head';

export default function Page() {
  return (
    <>
    <Head>
      <title>ROAS Calculator - Return on Ad Spend Calculator</title>
      <meta name="description" content="Calculate your Return on Ad Spend (ROAS) to measure advertising effectiveness. Enter your ad spend and revenue to determine if your campaigns are profitable." />
    </Head>
    <div className="min-h-screen flex flex-col">
      {/* Navbar */}
      <section className="bg-base-100">
        <Navbar />
      </section>

      {/* Main Content */}
      <section className="bg-base-200 text-black flex-grow">
        <div className="max-w-3xl mx-auto px-8 pt-24">
          {/* Page Title */}
          <h1 className="text-4xl font-bold mb-6 text-center">ROAS Calculator</h1>

          {/* Intro / Overview */}
          <div className="bg-white text-black text-xl leading-loose p-8 rounded-lg shadow-sm mb-12 text-center">
            <p>
              Want to know if your ad campaigns are truly profitable? Our
              <strong> ROAS (Return on Ad Spend)</strong> Calculator breaks down how much
              revenue your ads generate for every dollar you spend. Just enter your total
              ad spend and revenue to see if your campaigns are hitting the mark—or need
              a strategic makeover.
            </p>
          </div>

          {/* Calculator Component */}
          <div className="bg-base-100 rounded-2xl p-4 mb-8">
            <ROASCalculator />
          </div>

          {/* How to Use */}
          <div className="bg-base-100 rounded-2xl p-4 mb-8">
            <h2 className="text-xl font-semibold mb-4">How to use this calculator</h2>
            <ul className="space-y-2 text-left">
              <li>1. Enter your total ad spend (e.g., for a specific campaign or timeframe)</li>
              <li>2. Input the total revenue generated by those ads</li>
              <li>3. Click “Calculate” to see your Return on Ad Spend (ROAS)</li>
              <li>4. Use the result to decide if you should scale, optimize, or pivot your campaign</li>
            </ul>
          </div>

          {/* Example Calculation */}
          <div className="bg-base-100 p-4 rounded-xl mb-8">
            <h2 className="text-xl font-semibold mb-2">Example Calculation</h2>
            <p className="mb-3">
              Suppose you spent <strong>$1,000</strong> on an ad campaign and earned 
              <strong> $3,500</strong> in revenue directly attributed to those ads.
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li><strong>ROAS:</strong> $3,500 ÷ $1,000 = 3.5</li>
              <li><strong>ROAS in %:</strong> 3.5 × 100 = 350%</li>
            </ul>
            <p className="mt-3">
              A ROAS of 3.5 (or 350%) means you’re making $3.50 for every $1 spent on ads—a sign 
              that your campaign is delivering strong returns.
            </p>
          </div>

          {/* FAQ Section */}
          <div className="bg-base-100 p-4 rounded-xl mb-12">
            <h2 className="text-xl font-semibold mb-4">Frequently Asked Questions</h2>
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold mb-1 text-lg">How is ROAS different from ROI?</h3>
                <p>
                  ROAS focuses specifically on the revenue generated from your ad spend,
                  whereas ROI factors in broader costs and profit. 
                  ROAS is a more targeted metric for ad performance.
                </p>
              </div>

              <div>
                <h3 className="font-semibold mb-1 text-lg">What is a “good” ROAS?</h3>
                <p>
                  A good ROAS varies by industry and profit margins. 
                  Many businesses aim for at least a 3:1 ratio (300%), 
                  but higher is always better. 
                  Compare your ROAS to past campaigns or industry benchmarks.
                </p>
              </div>

              <div>
                <h3 className="font-semibold mb-1 text-lg">Can I include indirect costs?</h3>
                <p>
                  ROAS typically looks at ad spend vs. direct revenue. 
                  If you want a full profitability picture, try using ROI 
                  (which factors in overhead, salaries, etc.).
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
    </>
  );
}
